name: Run Nifty Data Script and Save CSV

on:
  schedule:
    - cron: '50 2 * * 1-5'
 
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pandas yfinance

      - name: Run Python script
        run: python Extract_data.py

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add *.csv
          git commit -m "Update CSV files on $(date)"
          git push origin main
        env:
          REPO_KEY: ${{ secrets.GITHUB_TOKEN }}
